export const ORDER_STATUS_JNE = {
  CANCELLED: "CANCELLED",
  RECEIVED: "RECEIVED",
  RETURN_TO_SHIPPER: "RETURN TO SHIPPER",
  SHIPMENT_PROBLEM: "SHIPMENT PROBLEM",
  FAILED_PICKUP: "FAILED PICKUP",
  DELIVERED: "DELIVERED",
  PENDING: "Pending",
  SUCCESS_PICKUP: "SUCCESS PICKUP",
  SHIPPED: "SHIPPED",
  PENDING_PICKUP: "PENDING PICKUP",
};

export const ORDER_STATUS_NINJA = {
  DELIVERED: "Delivered",
  PICKUP: "Picked Up",
  DELIVERY_EXCEPTION: "Delivery Exception",
  RETURNED_TO_SENDER: "Returned to Sender",
};

export const ORDER_STATUS_SAP = {
  BEING_PICKUP: "ENTRI (SEDANG DI PICKUP)",
  PENDING_PICKUP: "ENTRI (PENDING PICKUP)",
  RE_PICKUP: "ENTRI (SEDANG PICKUP ULANG)",
  PICKED_UP: "PICKED UP",
  VOID: "VOID",
  VOID_PICKUP: "VOID PICKUP",
  VERIFIED: "ENTRI VERIFIED",
  MANIFEST_OUTGOING: "MANIFEST OUTGOING",
  OUTGOING_SMU: "OUTGOING SMU",
  INCOMING: "INCOMING",
  DELIVERY: "DELIVERY",
  POD_DELIVERED: "POD - DELIVERED",
  POD_UNDELIVERED: "POD - UNDELIVERED",
  OUTGOING_RETURN: "OUTGOING RETURN",
  INCOMING_RETURN: "INCOMING RETURN",
  DELIVERY_RETURN: "DELIVERY RETURN",
  SHIPMENT_RETURN_TO_CLIENT: "SHIPMENT RETURN TO CLIENT",
};

export const ORDER_STATUS_IDEXPRESS = {
  PICKUP_SCAN: "Pick up scan",
  SENDING_SCAN: "Sending scan",
  ARRIVAL_SCAN: "Arrival scan",
  DELIVERY_SCAN: "Delivery scan",
  POD_SCAN: "POD scan",
  RETURN_POD_SCAN: "Return POD Scan",
  PROBLEM_ON_SHIPMENT_SCAN: "Problem on Shipment scan",
  CONFIRM_RETURN_BILL: "Confirm Return Bill",
  PICKUP_FAILURE: "Pickup failure",
  DROPPED_OFF_AT_STORE: "Dropped Off at Store",
  AUTOMATIC_CANCEL: "Automatic Cancel",
};
